version: '2'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

  jobs:
    depends_on:
      - 'postgres'
      - 'redis'
      - 'app'
    build: .
    command: bash -c "bundle exec sidekiq -q emails"
    volumes:
      - '.:/usr/app/'
      - 'gem_cache:/gems'

  app:
    depends_on:
      - 'postgres'
      - 'redis'
    build: .
    command: bash -c "bundle exec puma -C config/puma.rb"
    ports:
      - '3000:3000'
    volumes:
      - '.:/usr/app/'
      - 'gem_cache:/gems'

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  redis:
  postgres:
  gem_cache: