# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba5291036b235a01f1c7df242f4e38f4382b8af641c0f148fc14ce73e6b3e4951c487f6032676db6e499051806b40266bcd3266c965246478a04a966414abceb

test:
  secret_key_base: 3978f1ba0c471d62f580fe145a6728839bcc49d8ad738e796850b7a083d14187244b3c2f956c3c46a857c65af0143a538c89fd99cb6bf320ac694ad3eb07b138

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
